const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257,
  },
  events: [
    {
      created: 1551856436000,
      duration: 4500000,
      id: 'gtmxsqyzlbbc',
      name: 'Vinyasa Yoga in der Ludwigsvorstadt',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566320400000,
      local_date: '2019-08-20',
      local_time: '19:00',
      updated: 1551856436000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25883905,
        name: 'Doina Yoga @Heilpraxisgemeinschaft',
        lat: 48.12617874145508,
        lon: 11.549954414367676,
        repinned: true,
        address_1: 'Grimmstraße 1',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1531374419000,
        name: 'Yoga Doina',
        id: 29215079,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Yoga-mit-Doina',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Yoga-mit-Doina/events/gtmxsqyzlbbc/',
      description: '<p>Yoga bedeutet Einheit. Ich bringe in meinen Yogastunden alles zusammen: Achtsamkeit, Energie, Ruhe, Kraft.<br/>Die richtige Musik trägt dich dabei durch die Vinyasas. In meinen 75min geht ihr durch alles: Zur Ruhe kommen, intensive Atmung, Power-Flows mit ordentlich Beat, Meditation und Entspannung.<br/>Indem du körperliche Kraft entwickelst, setzt du auch deine innere Kraft frei. Du wirst durch das Üben immer bewusster und trägst dieses Bewusstsein von der Matte in dein Leben.<br/>Die Klasse kostet zwischen 10 - 20 Euro, zahl was du magst.<br/>BYOM - bring bitte deine eigene Matte mit. Falls du keine hast, sag mir Bescheid, ggf. kann ich dir eine mitbringen.</p> ',
      how_to_find_us: '3 Etage, rechts. Türe unten ist offen, wenn nicht bei Heilpraxis Kern klingeln.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1551856436000,
      duration: 4500000,
      id: 'gtmxsqyznblb',
      name: 'Vinyasa Yoga in der Ludwigsvorstadt',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1570554000000,
      local_date: '2019-10-08',
      local_time: '19:00',
      updated: 1551856436000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 25883905,
        name: 'Doina Yoga @Heilpraxisgemeinschaft',
        lat: 48.12617874145508,
        lon: 11.549954414367676,
        repinned: true,
        address_1: 'Grimmstraße 1',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1531374419000,
        name: 'Yoga Doina',
        id: 29215079,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Yoga-mit-Doina',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Yoga-mit-Doina/events/gtmxsqyznblb/',
      description: '<p>Yoga bedeutet Einheit. Ich bringe in meinen Yogastunden alles zusammen: Achtsamkeit, Energie, Ruhe, Kraft.<br/>Die richtige Musik trägt dich dabei durch die Vinyasas. In meinen 75min geht ihr durch alles: Zur Ruhe kommen, intensive Atmung, Power-Flows mit ordentlich Beat, Meditation und Entspannung.<br/>Indem du körperliche Kraft entwickelst, setzt du auch deine innere Kraft frei. Du wirst durch das Üben immer bewusster und trägst dieses Bewusstsein von der Matte in dein Leben.<br/>Die Klasse kostet zwischen 10 - 20 Euro, zahl was du magst.<br/>BYOM - bring bitte deine eigene Matte mit. Falls du keine hast, sag mir Bescheid, ggf. kann ich dir eine mitbringen.</p> ',
      how_to_find_us: '3 Etage, rechts. Türe unten ist offen, wenn nicht bei Heilpraxis Kern klingeln.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      local_time: '15:00',
      local_date: '2019-08-18',
      link: 'https://www.meetup.com/Djembe-and-Percussion-Fun-Munchen/events/lqqtbryzlbxb/',
      visibility: 'public_limited',
      group: {
        created: 1376421848000,
        name: 'Djembe and Percussion Fun Muenchen',
        id: 9795322,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Djembe-and-Percussion-Fun-Munchen',
        who: 'Munich Percussionists',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      waitlist_count: 0,
      yes_rsvp_count: 1,
      duration: 14400000,
      time: 1566133200000,
      utc_offset: 7200000,
      name: 'Sonniger Sonntag - E-Garten',
      id: 'lqqtbryzlbxb',
    },
    {
      created: 1551856436000,
      duration: 4500000,
      id: 'gtmxsqyznbcb',
      name: 'Vinyasa Yoga in der Ludwigsvorstadt',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1569949200000,
      local_date: '2019-10-01',
      local_time: '19:00',
      updated: 1551856436000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25883905,
        name: 'Doina Yoga @Heilpraxisgemeinschaft',
        lat: 48.12617874145508,
        lon: 11.549954414367676,
        repinned: true,
        address_1: 'Grimmstraße 1',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1531374419000,
        name: 'Yoga Doina',
        id: 29215079,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Yoga-mit-Doina',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Yoga-mit-Doina/events/gtmxsqyznbcb/',
      description: '<p>Yoga bedeutet Einheit. Ich bringe in meinen Yogastunden alles zusammen: Achtsamkeit, Energie, Ruhe, Kraft.<br/>Die richtige Musik trägt dich dabei durch die Vinyasas. In meinen 75min geht ihr durch alles: Zur Ruhe kommen, intensive Atmung, Power-Flows mit ordentlich Beat, Meditation und Entspannung.<br/>Indem du körperliche Kraft entwickelst, setzt du auch deine innere Kraft frei. Du wirst durch das Üben immer bewusster und trägst dieses Bewusstsein von der Matte in dein Leben.<br/>Die Klasse kostet zwischen 10 - 20 Euro, zahl was du magst.<br/>BYOM - bring bitte deine eigene Matte mit. Falls du keine hast, sag mir Bescheid, ggf. kann ich dir eine mitbringen.</p> ',
      how_to_find_us: '3 Etage, rechts. Türe unten ist offen, wenn nicht bei Heilpraxis Kern klingeln.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1563609868000,
      duration: 5400000,
      id: 'lxgjfryzmbwb',
      name: 'Yoga für Männer',
      rsvp_limit: 9,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1568742300000,
      local_date: '2019-09-17',
      local_time: '19:45',
      updated: 1563609868000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 25923646,
        name: 'Fraunbergstudio',
        lat: 48.10029602050781,
        lon: 11.545408248901367,
        repinned: true,
        address_1: 'Fraunbergstrasse 3',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1448483136000,
        name: 'München - Yoga for the people',
        id: 19154881,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Yoga-for-the-people',
        who: 'Yogis',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Munchen-Yoga-for-the-people/events/lxgjfryzmbwb/',
      description: '<p>Nach langen Arbeitstagen im Büro bist Du ausgebrannt und müde. Intensiven Situationen gehst Du aus dem Weg. Du bist angespannt und fühlst Deinen Körper nicht.</p> <p>Yoga? Zu esoterisch, dafür bist Du zu männlich. Erzähl Deinen Kumpels einfach, Du gehst zum Kickboxen und nutze die Vorteile dieses jahrtausendealten Übungssystems, welches von je her von Männern praktiziert wurde :</p> <p>- Deine Gedanken sind klar<br/>- Du bist ruhig und gelassen<br/>- Du bist präsent und fokussiert<br/>- Deine Sinneswahrnehmungen sind scharf<br/>- Dein Sexleben ist intensiv<br/>- Du bist bei Dir<br/>- Dein Körper ist flexibel und stark</p> <p>Komme vorbei und überzeuge Dich selbst.</p> <p>Egal, ob Du neu bist oder schon Yoga-Erfahrung mitbringst. Zusammen üben wir Atem-, Körperübungen, Meditation und Tiefenentspannung.</p> <p>Ich unterrichte Yoga seit 8 Jahren mit großer Begeisterung.</p> <p>Yogamatten und Sitzkissen sind bereits vorhanden. Komm einfach in lockerer Sportkleidung (Jogginghose / Tshirt).</p> <p>Für Fragen : Schreib mir über meetup bzw. 01511/[masked].</p> <p>15€ p.P. / Session<br/>Schnupperpreis 10€ (für erstmalige Teilnahme)</p> <p>Ich freue mich auf Dich!</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1557417432000,
      duration: 3600000,
      id: 'hpwxxqyzlbkc',
      name: 'Outdoor Training [Natural Movement]',
      rsvp_limit: 5,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566927000000,
      local_date: '2019-08-27',
      local_time: '19:30',
      rsvp_close_offset: 'PT3H',
      updated: 1557417432000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26215358,
        name: 'Westpark',
        lat: 48.12034225463867,
        lon: 11.511041641235352,
        repinned: true,
        address_1: 'Specklinplatz',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1551533080000,
        name: 'MovNat München [Natural Movement Fitness]',
        id: 31289377,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'MovNat-Munchen-Natural-Movement-Fitness',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/MovNat-Munchen-Natural-Movement-Fitness/events/hpwxxqyzlbkc/',
      description: '<p>Unser Dienstagstraining im Westpark</p> <p>Zweite Trainingseinheit 19:30 bis 20:30 Uhr</p> <p>Ein Probetraining ist kostenlos. Bitte kontaktiere uns auf jeden Fall vorher bis spätestens 16:30 Uhr am gleichen Tag per E-Mail wenn du kommen möchtest falls es einen spontanen Wechsel des Treffpunkts gibt.</p> <p>Wir freuen uns auf dich!</p> <p>Alle weiteren Trainings:<br/>5er-Karte: 70,-€ / 10er-Karte: 120,-€<br/>3-Monatskarte: 70,-€/Monat<br/>6- Monatskarte: 60,-€/Monat</p> ',
      how_to_find_us: 'Schreibe uns für den genauen Treffpunkt',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      local_time: '19:30',
      local_date: '2019-09-11',
      link: 'https://www.meetup.com/Munchen-Indie-Meetup/events/263266744/',
      visibility: 'public_limited',
      group: {
        created: 1498855310000,
        name: 'München Indie Meetup',
        id: 24765976,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Indie-Meetup',
        who: 'Indies',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      waitlist_count: 0,
      yes_rsvp_count: 3,
      duration: 10800000,
      time: 1568223000000,
      utc_offset: 7200000,
      name: 'Minami Deutsch & Konstantin Unwohl',
      id: '263266744',
    },
    {
      local_time: '19:00',
      local_date: '2019-10-11',
      link: 'https://www.meetup.com/Munchen-Indie-Meetup/events/259426836/',
      visibility: 'public_limited',
      group: {
        created: 1498855310000,
        name: 'München Indie Meetup',
        id: 24765976,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Indie-Meetup',
        who: 'Indies',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      waitlist_count: 0,
      yes_rsvp_count: 3,
      duration: 10800000,
      time: 1570813200000,
      utc_offset: 7200000,
      name: 'Sisters of Mercy',
      id: '259426836',
    },
    {
      local_time: '17:50',
      local_date: '2019-08-20',
      link: 'https://www.meetup.com/munich-english-yoga-meeutp/events/263862880/',
      visibility: 'public_limited',
      group: {
        created: 1562661524000,
        name: 'Munich English Yoga Meetup I Free | City center I Join us',
        id: 32349747,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'munich-english-yoga-meeutp',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      waitlist_count: 0,
      yes_rsvp_count: 10,
      duration: 4200000,
      time: 1566316200000,
      utc_offset: 7200000,
      name: 'Rooftop Yoga (Mindspace 📍 near Stachus) ***Bring your mat***',
      id: '263862880',
    },
    {
      created: 1564906695000,
      duration: 10800000,
      id: '263716641',
      name: 'Shut Up & Write!™ Munich',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566316800000,
      local_date: '2019-08-20',
      local_time: '18:00',
      rsvp_open_offset: 'PT172H',
      updated: 1565711923000,
      utc_offset: 7200000,
      waitlist_count: 2,
      yes_rsvp_count: 10,
      venue: {
        id: 26570011,
        name: 'B.good, Weißenburger Straße 36',
        lat: 48.128231048583984,
        lon: 11.6006498336792,
        repinned: false,
        address_1: 'Weißenburger Straße 36',
        city: 'Munich ',
        country: 'DE',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1532540208000,
        name: 'Shut Up & Write!® Munich',
        id: 29351354,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'shutupandwritemunich',
        who: 'Writers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/shutupandwritemunich/events/263716641/',
      description: '<p>Join us for an hour of writing! We’ve discovered that it’s strikingly helpful to write with other writers.</p> <p>Be it a book, blog, script, essay, dissertation, resume, melody, poem or just plain work stuff, you are invited to write it with us. No one will see what you\'ve written or give you unsolicited advice. Instead of just thinking about writing, come and get some real writing done.<br/>SCHEDULE (roughly):</p> <p>18:00 - SESSION 1: quick intros.<br/>18:15 - timer starts: write for 1 hour.<br/>19:15 - chat / take off / keep writing for another timed hour (starting at ~19:45).</p> <p>OPTIONAL SOCIALIZING happens after we\'re done with the first/second writing hour. Writing is very solitary. Connecting (and sometimes even commiserating) with other writers is a cool thing.<br/>BEING LATE IS OKAY: just show up and get settled, then check-in with me after the session. (I’ll be the person with the Shut Up &amp; Write! sign.) If you were on time, please be willing to make room for the friendly latecomer.<br/>Happy writing and I look forward to seeing you!</p> <p>What Should I Bring?<br/>Whatever you need to be able to write!<br/>Bring earbuds/earplugs if you want to block the cafe’s overhead music or the occasional conversation by other patrons.<br/>There should be enough sockets to charge your devices, but make sure to charge them just in case! :)</p> <p>Other Important Details:<br/>GUIDELINES: Please thank our hosts by purchasing something.<br/>FUTURE LOCATIONS: If you have ideas about where and when we should meet, please share them! :)<br/>If you\'re on the waiting list, but still really really want to come, feel free to drop by — but in case we end up being too large of a group to manage, or we don\'t find enough free seats, the priority is on the folks with the \'going\' RSVPs!</p> ',
      how_to_find_us: 'Look for the Shut up & Write! sign or ask for Stefka',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
	{
      created: 1563720667000,
      duration: 14400000,
      id: 'npdtgryzlbnc',
      name: 'Friday Social Drinks',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1567188000000,
      local_date: '2019-08-30',
      local_time: '20:00',
      updated: 1566060164000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26318541,
        name: 'The Cave',
        lat: 48.15903854370117,
        lon: 11.586549758911133,
        repinned: false,
        address_1: 'Nikolaistraße 9a',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1557680536000,
        name: 'Munich Social Drinks',
        id: 31885488,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Friday-Drinks-Social',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Friday-Drinks-Social/events/npdtgryzlbnc/',
      description: '<p>Join us for Friday Drinks and meet new people! Everybody is welcome. Feel free to bring along other people. The event will take place in the cosy Bar Restaurant \'The Cave\'. See you! :)))</p> <p>Cheers / Prost<br/>Martin</p> ',
      how_to_find_us: 'Ask a staff member for our Table. Or watch out for the sign NEU IN MÜNCHEN on our table. Fragt nach unserem Tisch. Es werden ebenfalls Hinweiszettel drauf sein.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1564908591000,
      duration: 32400000,
      id: '263716910',
      name: 'Styling fürs Oktoberfest: Fashiondeluxxe Wiesn ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1569049200000,
      local_date: '2019-09-21',
      local_time: '09:00',
      updated: 1564909922000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26553014,
        name: 'AWA Hotel',
        lat: 48.13827896118164,
        lon: 11.560914039611816,
        repinned: false,
        address_1: 'Schillerstr. 10',
        city: 'München ',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1551514362000,
        name: 'Beauty & Fashion Events in München',
        id: 31288103,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Fashiondeluxxe-Beauty-Fashion-Events-in-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Fashiondeluxxe-Beauty-Fashion-Events-in-Munchen/events/263716910/',
      description: '<p>Styling Lounge: Samstag und Sonntag,[masked] [masked]<br/>im AWA Hotel, Schillerstraße 10, 80336 München jeweils von 9 Uhr bis 18 Uhr</p> <p>Exklusives Business Networking Wiesn Frühstück: Sonntag,[masked] im Café Kaiserschmarrn (Rischart) auf dem Oktoberfest von 11.15 Uhr bis 13.15 Uhr</p> <p>Programmpunkte Styling Lounge:<br/>&gt; Styling Termine für den perfekten Wiesn Look<br/>&gt; Trachtige Shopping Corner mit exklusivem 20% Shoppingrabatt<br/>&gt; VIP Networking Lounge inkl. Food &amp; Drinks<br/>&gt; Dirndl Styling Workshop by Jasmin Leheta<br/>&gt; Business Speed Dating in der Networking Lounge by Mediadeluxxe<br/>&gt; Wiesn Photobooth mit Gewinnspiel by Mediadeluxxe<br/>&gt; Candybar by Mediadeluxxe<br/>&gt; Wiesn Goodie Bags<br/>&gt; Charity-Aktion: Tombola für den guten Zweck<br/>Weiteres Rahmenprogramm ist geplant und wird nach und nach auf unserer Website veröffentlicht.</p> <p>Mitglieder der Mediadeluxxe Networking Community:<br/>&gt; 15% Ticketrabatt (Styling Lounge)<br/>&gt; 1 kostenfreier Wiesn Styling Termin nach Wahl in der Styling Lounge (Termin am[masked] oder am[masked])<br/>&gt; Vorrang Buchung – Teilnahme am exklusiven Business Networking Wiesn Frühstück auf dem Oktoberfest am[masked] (limitiert auf 30 Personen!)<br/>&gt; 1 Glas Sekt umsonst bei Teilnahme am exklusiven Business Networking Wiesn Frühstück auf dem Oktoberfest am[masked]<br/>Jetzt Mitglied werden: </p><p>Informationen für Gäste (Eintritt, Anmeldung, Styling Termine etc.) werden erst im September online gestellt. Erst dann ist eine Anmeldung als Gast zum Event möglich.</p> <p>Aktuell sucht Mediadeluxxe Eventpartner für die Veranstaltung: Du möchtest deine Produkte/Dienstleistungen mit einem Verkaufsstand/einem Tombolapreis/einer Special Aktion o.ä. auf dem Event präsentieren? Du möchtest unsere Gäste in einem exklusiven Workshop/Vortrag direkt ansprechen und so einen Bezug zur Marke aufbauen? Du bist ein Dirndl Label und möchtest an der Trachtenmodenschau teilnehmen? Bitte wende dich direkt an Nathalie Dorff, Inhaberin von Mediadeluxxe.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1564908771000,
      duration: 32400000,
      id: '263716927',
      name: 'Styling fürs Oktoberfest: Fashiondeluxxe Wiesn ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1569135600000,
      local_date: '2019-09-22',
      local_time: '09:00',
      updated: 1564909953000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26553018,
        name: 'AWA Hotel',
        lat: 48.13827896118164,
        lon: 11.560914039611816,
        repinned: false,
        address_1: 'Schillerstrasse 10',
        address_2: '80336',
        city: 'München ',
        country: 'DE',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1551514362000,
        name: 'Beauty & Fashion Events in München',
        id: 31288103,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Fashiondeluxxe-Beauty-Fashion-Events-in-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Fashiondeluxxe-Beauty-Fashion-Events-in-Munchen/events/263716927/',
      description: '<p>Styling Lounge: Samstag und Sonntag,[masked] [masked]<br/>im AWA Hotel, Schillerstraße 10, 80336 München jeweils von 9 Uhr bis 18 Uhr</p> <p>Exklusives Business Networking Wiesn Frühstück: Sonntag,[masked] im Café Kaiserschmarrn (Rischart) auf dem Oktoberfest von 11.15 Uhr bis 13.15 Uhr</p> <p>Programmpunkte Styling Lounge:<br/>&gt; Styling Termine für den perfekten Wiesn Look<br/>&gt; Trachtige Shopping Corner mit exklusivem 20% Shoppingrabatt<br/>&gt; VIP Networking Lounge inkl. Food &amp; Drinks<br/>&gt; Dirndl Styling Workshop by Jasmin Leheta<br/>&gt; Business Speed Dating in der Networking Lounge by Mediadeluxxe<br/>&gt; Wiesn Photobooth mit Gewinnspiel by Mediadeluxxe<br/>&gt; Candybar by Mediadeluxxe<br/>&gt; Wiesn Goodie Bags<br/>&gt; Charity-Aktion: Tombola für den guten Zweck<br/>Weiteres Rahmenprogramm ist geplant und wird nach und nach auf unserer Website veröffentlicht.</p> <p>Mitglieder der Mediadeluxxe Networking Community:<br/>&gt; 15% Ticketrabatt (Styling Lounge)<br/>&gt; 1 kostenfreier Wiesn Styling Termin nach Wahl in der Styling Lounge (Termin am[masked] oder am[masked])<br/>&gt; Vorrang Buchung – Teilnahme am exklusiven Business Networking Wiesn Frühstück auf dem Oktoberfest am[masked] (limitiert auf 30 Personen!)<br/>&gt; 1 Glas Sekt umsonst bei Teilnahme am exklusiven Business Networking Wiesn Frühstück auf dem Oktoberfest am[masked]<br/>Jetzt Mitglied werden: </p> <p>Weitere Infos zur Styling Lounge/Fashiondeluxxe Wiesn: </p> <p>Informationen für Gäste (Eintritt, Anmeldung, Styling Termine etc.) werden erst im September online gestellt. Erst dann ist eine Anmeldung als Gast zum Event möglich.</p> <p>Aktuell sucht Mediadeluxxe Eventpartner für die Veranstaltung: Du möchtest deine Produkte/Dienstleistungen mit einem Verkaufsstand/einem Tombolapreis/einer Special Aktion o.ä. auf dem Event präsentieren? Du möchtest unsere Gäste in einem exklusiven Workshop/Vortrag direkt ansprechen und so einen Bezug zur Marke aufbauen? Du bist ein Dirndl Label und möchtest an der Trachtenmodenschau teilnehmen? Bitte wende dich direkt an Nathalie Dorff, Inhaberin von Mediadeluxxe.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1565602103000,
      duration: 10800000,
      id: '263934160',
      name: 'Java by Comparison',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1570640400000,
      local_date: '2019-10-09',
      local_time: '19:00',
      updated: 1565602168000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 39,
      group: {
        created: 1347703211000,
        name: 'Lightweight Java User Group München',
        id: 4939632,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Lightweight-Java-User-Group-Munchen',
        who: 'Lightweights',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Lightweight-Java-User-Group-Munchen/events/263934160/',
      description: '<p>Auf Basis von über 6 Jahren Java Lehre an der Uni Bamberg und dem Korrigieren von unzähligen Java-Aufgaben haben wir (Jörg Lenhard, Linus Dietz und Simon Harrer) ein Buch geschrieben, welches die typischen Fehler in einer innovativen Vorher/Nachher-Darstellung aufzeigt und erklärt: Java by Comparison [1].</p> <p>Durch diese Vergleiche können Einsteigerinnen und Einsteiger schneller eine Intuition für “Clean Code” entwickeln, Profis hilft es ihre Denkweisen Einsteigern besser zu erklären und vielleicht das eine oder andere aufzufrischen.</p> <p>Wir stellen erst die Geschichte des Buches vor und gehen dann konkret auf ein paar der Vergleiche aus dem Buch ein. Danach wollen wir gemeinsam kreativ sein und mit euch ein von uns entwickeltes Spiel namens “Comparison Jeopardy” [2] spielen. Wir freuen uns auf euch.</p> <p>[1] <br/>[2] </p> <p>Dr. Simon Harrer ist Senior Consultant bei INNOQ. Er kämpft tagtäglich für einfache Lösungen mit Domain-driven Design, passende Architekturen mit Microservices oder Monolithen und sauberen Code in Java, Ruby und sogar JavaScript. Mit dem Wissen aus seiner Zeit als Dozent an der Uni Bamberg hat er an dem Buch Java by Comparison mitgearbeitet, das Anfängern mittels Vorher/Nachher-Beispielen beibringt saubereren Java Code zu schreiben. Seit dem er mit einem Team Remote Mob Programming ausprobiert hat, möchte er nie wieder anders arbeiten.</p> <p>Linus Dietz ist Wissenschaftlicher Mitarbeiter an der Fakultät für Informatik der Technischen Uni München. Er forscht dort zu Empfehlungsdiensten für Reisende und Mobilität im Generellen. Zuvor hat er zusammen mit Simon an der Uni Bamberg Programmierung in Java unterrichtet und den dort gewonnenen Erfahrungsschatz in Form des Buches Java by Comparison aufgeschrieben.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1565604375000,
      duration: 10800000,
      id: '263934715',
      name: 'Stream Processing Essentials with Hazelcast Jet: The World Beyond Batching',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571850000000,
      local_date: '2019-10-23',
      local_time: '19:00',
      updated: 1565604400000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 33,
      group: {
        created: 1347703211000,
        name: 'Lightweight Java User Group München',
        id: 4939632,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Lightweight-Java-User-Group-Munchen',
        who: 'Lightweights',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Lightweight-Java-User-Group-Munchen/events/263934715/',
      description: '<p>Batch processing served us well for last 10s of years. Most of developers have a good idea what does it mean to design &amp; implement a batch processing system. However business often requires real-time insight into big data. The talk will walk through basic concepts of stream processing. Then we will discuss the notion of time in a streaming system, aggregations and windowing. We will also touch some of the operational concerns unique to stream processing and complement our understanding with some cool application demonstrations.</p> <p>Speaker Bio:</p> <p>Emin Demirci leads the integration efforts of Hazelcast Jet with the outer world. Prior to that, he had to get his hands dirty with all the moving parts of the product family of Hazelcast, from implementing new features to creating fancy UIs. Before joining to Hazelcast, Emin did an internship at PGS Software and Hazelcast. He holds a BSc. degree in Computer Engineering from Karadeniz Technical University. He is a petrolhead, enjoys playing football (also proud to be a fan of Galatasaray) and cycling.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1563570122000,
      duration: 10800000,
      id: '263298410',
      name: 'Killswitch Engage @ Tonhalle',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573063200000,
      local_date: '2019-11-06',
      local_time: '19:00',
      updated: 1563570122000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26045017,
        name: 'TonHalle München',
        lat: 48.12398910522461,
        lon: 11.607072830200195,
        repinned: false,
        address_1: 'Atelierstraße 24',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1527269716000,
        name: 'Munich Heavy Metal Meetup',
        id: 28598723,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Heavy-Metal-Meetup',
        who: 'Metalheads',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Munich-Heavy-Metal-Meetup/events/263298410/',
      description: '<p>Tickets: </p> ',
      how_to_find_us: 'message me',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      local_time: '20:00',
      local_date: '2019-08-30',
      link: 'https://www.meetup.com/Munchen-Indie-Meetup/events/259451174/',
      visibility: 'public_limited',
      group: {
        created: 1498855310000,
        name: 'München Indie Meetup',
        id: 24765976,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Indie-Meetup',
        who: 'Indies',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      waitlist_count: 0,
      yes_rsvp_count: 3,
      duration: 10800000,
      time: 1567188000000,
      utc_offset: 7200000,
      name: 'Oh Sees',
      id: '259451174',
    },
    {
      created: 1564340273000,
      duration: 3600000,
      id: '263534567',
      name: 'Eisbachbaden plus Wim Hof Meditation',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566711900000,
      local_date: '2019-08-25',
      local_time: '07:45',
      updated: 1564340278000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26309138,
        name: 'Milchhäusl',
        lat: 48.149776458740234,
        lon: 11.58552074432373,
        repinned: false,
        address_1: 'Veterinärstraße 16',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1506234183000,
        name: 'Wild und Frei -  Eisbaden | Improtheater | Waldbaden',
        id: 26034273,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Next-Level-Meditation-wie-du-alles-erreichen-kannst',
        who: 'Genießer',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Next-Level-Meditation-wie-du-alles-erreichen-kannst/events/263534567/',
      description: '<p>Du willst mal wieder richtig geil in Deinen Sonntag starten?</p> <p>Dann bieten wir Dir am 25. August die perfekte Möglichkeit!</p> <p>Wim Hof hält den Weltrekord im Eisbaden und er hat eine Meditation entwickelt, die Dir hilft länger in der Kälte zu bleiben.</p> <p>Wir treffen uns morgens um Viertel vor 8 am Milchhäusl (direkt am Eingang zum Englischen Garten von der U-Bahn Universität aus) und legen dann um 8:00 Uhr mit der Meditation los (Dauer ca. 15 Minuten). Danach geht\'s noch in den Eisbach, die Abhärtung für den nächsten Winter beginnt;)</p> <p>Außerdem ist das Gefühl nach dem (Eis)bachbaden morgens unbeschreiblich und es soll auch noch gesund sein hab ich gehört.</p> <p>Mitbringen: Handtuch sonst nichts</p> <p>Teilnahme for free!</p> <p>Wir sehen uns im Eisbach,<br/>Roman</p> <p>Nummer für alle Fälle:[masked]</p> <p>PS: Danach geht\'s noch gemeinsam frühstücken ins CADU</p> <p>Liket uns auf Facebook:</p> ',
      how_to_find_us: '5 Minuten von der U Bahn Station Universität aus Richtung Englischer Garten',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1564917329000,
      duration: 9000000,
      id: '263718476',
      name: 'Workshop: Diversity in leading through transition: home building at work',
      rsvp_limit: 75,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1567701000000,
      local_date: '2019-09-05',
      local_time: '18:30',
      updated: 1564917347000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 23,
      venue: {
        id: 25615449,
        name: 'Henley Business School Germany',
        lat: 48.13788604736328,
        lon: 11.583979606628418,
        repinned: true,
        address_1: 'Maximilianstraße 40',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1510684582000,
        name: 'Leadership Events - München',
        id: 26598849,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Leadership-Events-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Leadership-Events-Munchen/events/263718476/',
      description: '<p>The role of diversity is getting its deserved attention in current discussions on how to lead effectively through change.</p> <p>Adding the voice of those concerned, Henley alumna and leadership coach Rania Roelofs (MSc in Coaching and Behavioural Change) looks at how ultimately, leaders themselves experience these processes as highly individual, changing through time and \'place\' - our feeling of being in a position to utilize diverse aspects of ourselves as resources and bring our full potential to work.</p> <p>What then, Rania wonders, are common characteristics of \'place\' that potentially support change leaders bringing their whole selves as resources in taking up their organizational roles? She then invites us to creatively switch perspective and explore the issue through the lens of the concept of \'homebuilding\', from a discipline with longstanding expertise in the study of \'changes of place\' - social anthropology and more specific, migrant studies.</p> <p>We are happy to have Rania Roelofs present her insights on the role of \'homebuilding\' at work. Using current thinking and experiential learning, in a stimulating and hands-on learning format, we will reflect on the room we might be able to create for ourselves to effectively take the lead through our next organizational change. At the end, you will choose from your own and others’ real-life leadership transition experiences, which equipment can help to deal with permanent change and raise awareness of what you and your team might need to feel at home during permanent change, so that you bring yourself and your whole potential into your role.</p> <p>As always, we start with a networking reception at 18.30 hrs, followed by the workshop at 19.00 hrs. We plan on finishing at 21.00 hrs and ending with half an hour of networking. The workshop will be conducted in English.</p> <p>We look forward to seeing you on 5 September!</p> ',
      how_to_find_us: 'Please note: The entrance is along Thomas-Wimmer-Ring in the direction of Isartor, immediately before the intersection with Hildegardstraße.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1563716130000,
      duration: 10800000,
      id: '263334128',
      name: 'Our second Flutter Study Jam',
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1569945600000,
      local_date: '2019-10-01',
      local_time: '18:00',
      updated: 1565717673000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 25,
      venue: {
        id: 26082467,
        name: 'codecentric AG',
        lat: 48.13685989379883,
        lon: 11.523862838745117,
        repinned: true,
        address_1: 'Elsenheimerstraße 55A',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1543101111000,
        name: 'Flutter Munich',
        id: 30587470,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Flutter-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Flutter-Munich/events/263334128/',
      description: '<p>I’d like to invite all of you to our second study jam. The concept is simple: we meet and we create beautiful apps together.</p> <p>Flutter is Google’s portable UI toolkit for building beautiful, natively-compiled applications for mobile, web, and desktop from a single codebase.</p> <p>Flutter Study Jams are a great opportunity to get together to learn and practice this technology in person.</p> <p>👨\u200d💻We prepared a list of awesome tutorials, so you can create something on your own, all the while we are there to help you in case you get stuck.<br/>🐧You can also bring your own ideas or work on open-source projects.<br/>❓You can come with questions, we’ll do our best to help you with any issue you bring.<br/>🎤At the end of the event, you’ll have the opportunity to show to the rest of us what you worked on (presenting is optional, but encouraged).</p> <p>The event is best for people who already know how to code in at least one programming language.</p> <p>IMPORTANT</p> <p>💻You need to bring your own computer.<br/>📱Bring cables to connect your phone to your laptop, if you’d like to develop on a physical device (aka mobile phone).<br/>⚡Don’t forget your charger.<br/>👩\u200d💻Finish the Installation Guide before the event.><br/>🏎Finish the Test drive before the event></p> <p>LOCATION</p> <p>📍The event is hosted by codecentric. Address: Elsenheimerstraße 55A, 80687 Münchea></p> ',
      how_to_find_us: 'Just follow the Flutter Meetup signs and arrows. Enter the main entrance, turn right and come up to the 4th floor.',
      visibility: 'public',
      member_pay_fee: false,
    },
  ],
};

export { mockEvents };
